### ISSUE TITLE
Slightly improved user experience by changing links

### ISSUE THREAD

**Issue by Oryfox** [johanneslosch/jlosch#10]
https://github.com/johanneslosch/jlosch/blob/34b5b56c5e4a4fe1d936c3a75e649368d844edf2/src/components/Navigation.vue#L20-L24

I just visited the website and recognized a short flickering when clicking the "Home" link in the navigation. I tried editing it in the inspection window of my browser and replacing "/" with "#" for the Home link maintains the functionality and removes the flickering.

You are maybe interested in this.

**Comment by johanneslosch** [comment]
done in dev branch
